//
// ofxPocoConfig.h
//
// Generated by scripts/update_poco.py. Included at the top of Poco/Config.h.
//
// These settings replace the compile definitions POCO's CMake build would
// set. Anything that changes a POCO header's meaning belongs here, so POCO's
// own sources and every file that includes a POCO header see the same values.
//

#ifndef ofxPocoConfig_INCLUDED
#define ofxPocoConfig_INCLUDED

// Marks these headers as ofxPocoHeaders' copy of POCO (see ofxPocoHeaders.h).
#define OFX_POCO_HEADERS 1
#define OFX_POCO_HEADERS_POCO_VERSION 0x010F0200

// POCO is compiled into the app as static code.
#ifndef POCO_STATIC
    #define POCO_STATIC 1
#endif

// Never emit MSVC #pragma comment(lib, ...) for prebuilt POCO libraries.
#ifndef POCO_NO_AUTOMATIC_LIBS
    #define POCO_NO_AUTOMATIC_LIBS 1
#endif

// FastLogger needs the bundled quill library, which is not vendored.
#ifndef POCO_NO_FASTLOGGER
    #define POCO_NO_FASTLOGGER 1
#endif

#if defined(__APPLE__)
    #include <TargetConditionals.h>
    #ifndef POCO_NO_STAT64
        #define POCO_NO_STAT64 1
    #endif
    #if TARGET_OS_IPHONE // iOS, tvOS, watchOS, visionOS and their simulators
        #ifndef POCO_NO_FPENVIRONMENT
            #define POCO_NO_FPENVIRONMENT 1
        #endif
        #ifndef POCO_NO_SHAREDLIBS
            #define POCO_NO_SHAREDLIBS 1
        #endif
        #ifndef POCO_NO_NET_IFTYPES
            #define POCO_NO_NET_IFTYPES 1
        #endif
    #endif
#elif defined(__ANDROID__)
    #ifndef POCO_NO_FPENVIRONMENT
        #define POCO_NO_FPENVIRONMENT 1
    #endif
    #ifndef POCO_NO_WSTRING
        #define POCO_NO_WSTRING 1
    #endif
    #ifndef POCO_NO_SHAREDMEMORY
        #define POCO_NO_SHAREDMEMORY 1
    #endif
#elif defined(__EMSCRIPTEN__)
    #ifndef POCO_NO_THREADNAME
        #define POCO_NO_THREADNAME 1
    #endif
#endif

#endif // ofxPocoConfig_INCLUDED
