// Generated by scripts/update_poco.py. Do not edit; rerun the script instead.
#define XML_DTD 1
#define XML_NS 1
#define XML_STATIC 1
#define HAVE_EXPAT_CONFIG_H 1
#if defined(__APPLE__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__)
    #define HAVE_ARC4RANDOM_BUF 1
#elif defined(__linux__) && !defined(__ANDROID__)
    #define HAVE_GETRANDOM 1
#elif !defined(_WIN32)
    #define XML_DEV_URANDOM 1
#endif
#include "../../source/dependencies/expat/src/xmltok_impl.c"
