//
// ofxPocoBuild.h
//
// Generated by scripts/update_poco.py. Included first by every generated
// POCO wrapper in libs/poco/src. Holds defines POCO's CMake sets only while
// compiling POCO itself; they must not leak into user code.
//

#pragma once

#if defined(__linux__) && !defined(__ANDROID__)
    #ifndef _REENTRANT
        #define _REENTRANT
    #endif
    #ifndef _THREAD_SAFE
        #define _THREAD_SAFE
    #endif
    #ifndef _LARGEFILE64_SOURCE
        #define _LARGEFILE64_SOURCE
    #endif
    #ifndef _FILE_OFFSET_BITS
        #define _FILE_OFFSET_BITS 64
    #endif
#endif

#if defined(_WIN32)
    #ifndef UNICODE
        #define UNICODE
    #endif
    #ifndef _UNICODE
        #define _UNICODE
    #endif
#endif

// Bundled third-party code is linked statically.
#ifndef PCRE2_STATIC
    #define PCRE2_STATIC 1
#endif
#ifndef HAVE_CONFIG_H
    #define HAVE_CONFIG_H 1
#endif
#ifndef UTF8PROC_STATIC
    #define UTF8PROC_STATIC 1
#endif
#ifndef XML_STATIC
    #define XML_STATIC 1
#endif
#ifndef XML_DTD
    #define XML_DTD 1
#endif
