#!/usr/bin/env python3
"""
Vendors the POCO C++ Libraries source into ofxPocoHeaders so POCO is compiled
as part of each openFrameworks project instead of being linked as prebuilt libs.

Layout produced (everything under libs/poco is regenerated on every run):

    libs/poco/include/Poco/...        public headers of all vendored modules
    libs/poco/source/<Module>/src     POCO sources, untouched except for the
                                      include patches listed in DEP_HEADERS
    libs/poco/source/dependencies/    bundled third-party code POCO needs
    libs/poco/src/<Module>/*.cpp|.c   generated one-line wrappers; these are
                                      the only files the OF build compiles

The wrappers let us mirror POCO's CMake rules without CMake: platform files
(Mutex_POSIX.cpp, ...) are never compiled on their own, platform-only sources
are guarded, and third-party code gets its private defines without leaking
them into the rest of the project.

Usage:
    scripts/update_poco.py [--version 1.15.2] [--source /path/to/poco]
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

ADDON_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POCO_DIR = os.path.join(ADDON_ROOT, "libs", "poco")

# POCO modules to vendor. Order does not matter.
# ofxPoco also shipped Data, Redis, Prometheus, ActiveRecord and PDF; they are
# left out to keep build times down (PDF would also bundle a second libpng).
MODULES = ["Foundation", "Net", "NetSSL_OpenSSL", "Crypto", "Util", "JSON", "XML",
           "Zip", "Encodings", "JWT"]

# Headers older POCO releases (and ofxPoco) shipped that 1.15 no longer has.
# Each forwards to the replacement so existing #includes keep compiling.
COMPAT_HEADERS = {
    # POCO < 1.12 bundled zlib and installed its headers as Poco/zlib.h and
    # Poco/zconf.h. openFrameworks provides zlib itself.
    "Poco/zlib.h": "#include <zlib.h>\n",
    "Poco/zconf.h": "#include <zconf.h>\n",
}

# Sources excluded by POCO's CMake (ENABLE_FASTLOGGER is off).
SKIP_SOURCES = {
    ("Foundation", "FastLogger.cpp"),
    ("Util", "FastLoggerConfigurator.cpp"),
}

# Sources CMake only adds on one platform (POCO_SOURCES_AUTO_PLAT).
PLATFORM_ONLY = {
    ("Foundation", "SyslogChannel.cpp"): "!defined(_WIN32)",
    ("Foundation", "WindowsConsoleChannel.cpp"): "defined(_WIN32)",
    ("Foundation", "EventLogChannel.cpp"): "defined(_WIN32)",
    ("Util", "WinRegistryConfiguration.cpp"): "defined(_WIN32)",
    ("Util", "WinRegistryKey.cpp"): "defined(_WIN32)",
    ("Util", "WinService.cpp"): "defined(_WIN32)",
}

# Bundled dependency headers that POCO sources include by bare name via CMake
# private include dirs. We rewrite those includes to relative paths so no
# third-party directory (with generic header names) lands on the project's
# include path. zlib is deliberately absent: POCO uses OF core's zlib.
DEP_HEADERS = {
    "pcre2.h": "pcre2",
    "pcre2_config.h": "pcre2",
    "pcre2_internal.h": "pcre2",
    "utf8proc.h": "utf8proc",
    "expat.h": "expat",
    "pdjson.h": "pdjson",
    "wepoll.h": "wepoll",
    "double-conversion.h": "v8_double_conversion",
    # Foundation/src/NumericString.cpp compiles double-conversion by
    # #including its sources.
    "bignum-dtoa.cc": "v8_double_conversion",
    "bignum.cc": "v8_double_conversion",
    "cached-powers.cc": "v8_double_conversion",
    "double-to-string.cc": "v8_double_conversion",
    "fast-dtoa.cc": "v8_double_conversion",
    "fixed-dtoa.cc": "v8_double_conversion",
    "string-to-double.cc": "v8_double_conversion",
    "strtod.cc": "v8_double_conversion",
}

# Bundled dependencies copied into source/dependencies.
# v8_double_conversion is copied but not compiled: Foundation's
# NumericString.cpp #includes all of its .cc files directly.
DEPENDENCIES = ["pcre2", "utf8proc", "expat", "pdjson", "wepoll", "v8_double_conversion"]

# Dependency C sources to compile, with the guard and private defines each gets.
EXPAT_PRELUDE = """#define XML_DTD 1
#define XML_NS 1
#define XML_STATIC 1
#define HAVE_EXPAT_CONFIG_H 1
#if defined(__APPLE__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__)
    #define HAVE_ARC4RANDOM_BUF 1
#elif defined(__linux__) && !defined(__ANDROID__)
    #define HAVE_GETRANDOM 1
#elif !defined(_WIN32)
    #define XML_DEV_URANDOM 1
#endif
"""

DEP_BUILD = {
    "pcre2": ("", "#define HAVE_CONFIG_H 1\n#define PCRE2_STATIC 1\n"),
    "utf8proc": ("", "#define UTF8PROC_STATIC 1\n"),
    "expat": ("", EXPAT_PRELUDE),
    "pdjson": ("", "#define _CRT_SECURE_NO_WARNINGS 1\n"),
    "wepoll": ("defined(_WIN32)", ""),
}

GENERATED_NOTE = "// Generated by scripts/update_poco.py. Do not edit; rerun the script instead.\n"

# Public config header, included from the top of Poco/Config.h so that POCO's
# own sources and user code always agree on these settings.
OFX_POCO_CONFIG = """//
// ofxPocoConfig.h
//
// Generated by scripts/update_poco.py. Included at the top of Poco/Config.h.
//
// These settings replace the compile definitions POCO's CMake build would
// set. Anything that changes a POCO header's meaning belongs here, so POCO's
// own sources and every file that includes a POCO header see the same values.
//

#ifndef ofxPocoConfig_INCLUDED
#define ofxPocoConfig_INCLUDED

// Marks these headers as ofxPocoHeaders' copy of POCO (see ofxPocoHeaders.h).
#define OFX_POCO_HEADERS 1
#define OFX_POCO_HEADERS_POCO_VERSION @POCO_VERSION_HEX@

// POCO is compiled into the app as static code.
#ifndef POCO_STATIC
    #define POCO_STATIC 1
#endif

// Never emit MSVC #pragma comment(lib, ...) for prebuilt POCO libraries.
#ifndef POCO_NO_AUTOMATIC_LIBS
    #define POCO_NO_AUTOMATIC_LIBS 1
#endif

// FastLogger needs the bundled quill library, which is not vendored.
#ifndef POCO_NO_FASTLOGGER
    #define POCO_NO_FASTLOGGER 1
#endif

#if defined(__APPLE__)
    #include <TargetConditionals.h>
    #ifndef POCO_NO_STAT64
        #define POCO_NO_STAT64 1
    #endif
    #if TARGET_OS_IPHONE // iOS, tvOS, watchOS, visionOS and their simulators
        #ifndef POCO_NO_FPENVIRONMENT
            #define POCO_NO_FPENVIRONMENT 1
        #endif
        #ifndef POCO_NO_SHAREDLIBS
            #define POCO_NO_SHAREDLIBS 1
        #endif
        #ifndef POCO_NO_NET_IFTYPES
            #define POCO_NO_NET_IFTYPES 1
        #endif
    #endif
#elif defined(__ANDROID__)
    #ifndef POCO_NO_FPENVIRONMENT
        #define POCO_NO_FPENVIRONMENT 1
    #endif
    #ifndef POCO_NO_WSTRING
        #define POCO_NO_WSTRING 1
    #endif
    #ifndef POCO_NO_SHAREDMEMORY
        #define POCO_NO_SHAREDMEMORY 1
    #endif
#elif defined(__EMSCRIPTEN__)
    #ifndef POCO_NO_THREADNAME
        #define POCO_NO_THREADNAME 1
    #endif
#endif

#endif // ofxPocoConfig_INCLUDED
"""

# Build-only prelude, included first by every POCO module wrapper.
OFX_POCO_BUILD = """//
// ofxPocoBuild.h
//
// Generated by scripts/update_poco.py. Included first by every generated
// POCO wrapper in libs/poco/src. Holds defines POCO's CMake sets only while
// compiling POCO itself; they must not leak into user code.
//

#pragma once

#if defined(__linux__) && !defined(__ANDROID__)
    #ifndef _REENTRANT
        #define _REENTRANT
    #endif
    #ifndef _THREAD_SAFE
        #define _THREAD_SAFE
    #endif
    #ifndef _LARGEFILE64_SOURCE
        #define _LARGEFILE64_SOURCE
    #endif
    #ifndef _FILE_OFFSET_BITS
        #define _FILE_OFFSET_BITS 64
    #endif
#endif

#if defined(_WIN32)
    #ifndef UNICODE
        #define UNICODE
    #endif
    #ifndef _UNICODE
        #define _UNICODE
    #endif
#endif

// Bundled third-party code is linked statically.
#ifndef PCRE2_STATIC
    #define PCRE2_STATIC 1
#endif
#ifndef HAVE_CONFIG_H
    #define HAVE_CONFIG_H 1
#endif
#ifndef UTF8PROC_STATIC
    #define UTF8PROC_STATIC 1
#endif
#ifndef XML_STATIC
    #define XML_STATIC 1
#endif
#ifndef XML_DTD
    #define XML_DTD 1
#endif
"""


def run(cmd, **kw):
    print("+ " + " ".join(cmd))
    subprocess.check_call(cmd, **kw)


def fetch_poco(version, dest):
    run(["git", "clone", "--quiet", "--depth", "1",
         "--branch", "poco-%s-release" % version,
         "https://github.com/pocoproject/poco.git", dest])


def read_version(src):
    with open(os.path.join(src, "VERSION")) as f:
        version = f.read().strip()
    major, minor, patch = (int(x) for x in re.match(r"(\d+)\.(\d+)\.(\d+)", version).groups())
    return version, "0x%02X%02X%02X00" % (major, minor, patch)


def included_sources(src_dir):
    """Sources another file in src_dir #includes (e.g. Mutex_POSIX.cpp).

    These are compiled as part of their includer, never on their own. POCO's
    CMake approximates this with a file-name rule (X_Y.cpp), which would wrongly
    skip sources such as Encodings' ISO8859_10Encoding.cpp in modules that do
    not use that rule, so we check the actual #includes instead.
    """
    found = set()
    for name in os.listdir(src_dir):
        if name.endswith((".cpp", ".h")):
            with open(os.path.join(src_dir, name), encoding="utf-8", errors="replace") as f:
                found.update(re.findall(r'#\s*include\s*"([^"/]+\.cpp)"', f.read()))
    return found


def patch_dep_includes(path, module_src_dir):
    with open(path, encoding="utf-8", errors="replace") as f:
        text = f.read()

    def repl(m):
        header = m.group(2)
        dep = DEP_HEADERS.get(header)
        if dep is None:
            return m.group(0)
        target = os.path.join(POCO_DIR, "source", "dependencies", dep, "src", header)
        rel = os.path.relpath(target, os.path.dirname(path)).replace(os.sep, "/")
        return '%s"%s"' % (m.group(1), rel)

    patched = re.sub(r'(#\s*include\s*)[<"]([^">]+)[">]', repl, text)
    if patched != text:
        with open(path, "w", encoding="utf-8") as f:
            f.write(patched)
        print("  patched includes: %s" % os.path.relpath(path, ADDON_ROOT))


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def wrapper(rel_include, prelude="", guard=""):
    body = '#include "%s"\n' % rel_include
    if guard:
        body = "#if %s\n%s#endif\n" % (guard, body)
    return GENERATED_NOTE + prelude + body


def cmake_excludes(cmake_file):
    with open(cmake_file) as f:
        return re.findall(r'EXCLUDE REGEX "\.\*([^"\\]+)(?:\\\\)?\.c"', f.read())


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--version", default="1.15.2")
    ap.add_argument("--source", help="existing POCO checkout (skips git clone)")
    args = ap.parse_args()

    tmp = None
    src = args.source
    if not src:
        tmp = tempfile.mkdtemp(prefix="ofxPocoHeaders-")
        src = os.path.join(tmp, "poco")
        fetch_poco(args.version, src)

    version, version_hex = read_version(src)
    print("Vendoring POCO %s from %s" % (version, src))

    shutil.rmtree(POCO_DIR, ignore_errors=True)
    include_dir = os.path.join(POCO_DIR, "include")
    source_dir = os.path.join(POCO_DIR, "source")
    wrap_dir = os.path.join(POCO_DIR, "src")

    # Public headers and module sources.
    for module in MODULES:
        shutil.copytree(os.path.join(src, module, "include"), include_dir, dirs_exist_ok=True)
        shutil.copytree(os.path.join(src, module, "src"), os.path.join(source_dir, module, "src"))

    # Header-only tessil ordered map is part of POCO's public headers.
    shutil.copytree(os.path.join(src, "dependencies", "tessil", "include"), include_dir, dirs_exist_ok=True)

    for dep in DEPENDENCIES:
        dep_src = os.path.join(src, "dependencies", dep)
        dep_dst = os.path.join(source_dir, "dependencies", dep)
        shutil.copytree(os.path.join(dep_src, "src"), os.path.join(dep_dst, "src"))
        for extra in ("LICENSE", "COPYING", "LICENSE.md", "README.md"):
            if os.path.exists(os.path.join(dep_src, extra)):
                shutil.copy(os.path.join(dep_src, extra), dep_dst)

    shutil.copy(os.path.join(src, "LICENSE"), os.path.join(POCO_DIR, "LICENSE"))
    shutil.copy(os.path.join(src, "VERSION"), os.path.join(POCO_DIR, "VERSION"))

    # Point bare dependency includes at the vendored copies.
    for module in MODULES:
        for root, _, files in os.walk(os.path.join(source_dir, module)):
            for name in files:
                if name.endswith((".cpp", ".h")):
                    patch_dep_includes(os.path.join(root, name), root)

    # Hook ofxPocoConfig.h into the top of Poco/Config.h.
    config_h = os.path.join(include_dir, "Poco", "Config.h")
    with open(config_h, encoding="utf-8") as f:
        text = f.read()
    guard = "#define Foundation_Config_INCLUDED\n"
    assert guard in text, "Poco/Config.h include guard not found"
    text = text.replace(guard, guard + '\n\n#include "Poco/ofxPocoConfig.h"\n', 1)
    write(config_h, text)
    write(os.path.join(include_dir, "Poco", "ofxPocoConfig.h"),
          OFX_POCO_CONFIG.replace("@POCO_VERSION_HEX@", version_hex))

    for header, body in COMPAT_HEADERS.items():
        path = os.path.join(include_dir, header)
        assert not os.path.exists(path), "%s now exists in POCO; drop the compat header" % header
        write(path, "// Compatibility header generated by scripts/update_poco.py.\n#pragma once\n" + body)

    # Wrappers for POCO modules.
    write(os.path.join(wrap_dir, "ofxPocoBuild.h"), OFX_POCO_BUILD)
    count = 0
    for module in MODULES:
        module_src = os.path.join(source_dir, module, "src")
        included = included_sources(module_src)
        for name in sorted(os.listdir(module_src)):
            if not name.endswith(".cpp") or (module, name) in SKIP_SOURCES or name in included:
                continue
            path = os.path.join(module_src, name)
            out = os.path.join(wrap_dir, module, "%s_%s" % (module, name))
            rel = os.path.relpath(path, os.path.dirname(out)).replace(os.sep, "/")
            write(out, wrapper(rel, '#include "../ofxPocoBuild.h"\n', PLATFORM_ONLY.get((module, name), "")))
            count += 1

    # Wrappers for bundled C dependencies.
    pcre2_excludes = set(cmake_excludes(os.path.join(src, "dependencies", "pcre2", "CMakeLists.txt")))
    for dep, (guard, prelude) in DEP_BUILD.items():
        dep_src = os.path.join(source_dir, "dependencies", dep, "src")
        for name in sorted(os.listdir(dep_src)):
            if not name.endswith(".c"):
                continue
            stem = name[:-2]
            if dep == "pcre2" and stem in pcre2_excludes:
                continue
            if dep == "utf8proc" and name == "utf8proc_data.c":
                continue  # #included by utf8proc.c
            out = os.path.join(wrap_dir, dep, "%s_%s" % (dep, name))
            rel = os.path.relpath(os.path.join(dep_src, name), os.path.dirname(out)).replace(os.sep, "/")
            write(out, wrapper(rel, prelude, guard))
            count += 1

    print("Generated %d wrappers for POCO %s (%s)" % (count, version, version_hex))
    if tmp:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
